version: '3'

services:
    registry: 
        build: registry
        ports: 
            - 9988:9988
    gateway:
        build: gateway
        ports:
            - 9889:9889
    channel-service:
        build: channel-service
        ports:
            - 8788:8788

    media-service:
        build: media-service
        ports:
            - 8789:8789

    postgres1:
        image: postgres:15.1
        ports:
             - 5000:5432

        environment:
            POSTGRES_USER: mirazul
            POSTGRES_PASSWORD: root123
            POSTGRES_DB: channeldb

    postgres2:
        image: postgres:15.1
        ports:
            - 5001:5432

        environment:
            POSTGRES_USER: mirazul
            POSTGRES_PASSWORD: root123
            POSTGRES_DB: mediadb



      
